language: python

addons:
  chrome: stable

python:
  - "2.7"
  - "3.6"

before_install:
  - mkdir /tmp/chromedriver
  - wget https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip -O /tmp/chromedriver/chromedriver.zip
  - unzip /tmp/chromedriver/chromedriver.zip -d /tmp/chromedriver
  - chmod 700 /tmp/chromedriver/chromedriver

install:
  - pip install -r requirements.txt

before_script:
  - export PATH=$PATH:/tmp/chromedriver
  - google-chrome-stable --version
  - chromedriver --version

script:
  - cat /etc/hosts
  - mv utils.py /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/selenium/webdriver/common/utils.py
  - python selenium_test.py
  - cat chromedriver.log
